name: build-vitruvio

on: 
  workflow_dispatch:
  push:
    # Careful! No fall-through for the filters.
    branches:
      - main
      - develop
      
  pull_request:
    # Careful! No fall-through for the filters.
    branches:
      - main
      - develop

env:
  CONFIG: ${{'--build-config=Shipping'}}
  # CONFIG: ${{github.ref == 'refs/heads/main' && '--build-config=Shipping' || '--build-config=Development'}}

jobs:
  package-host:
    runs-on: [self-hosted, zrh-unreal]
    name: Package host project
    steps:
      - uses: actions/checkout@v4
      - run: git -C C:\dev\git\zrh-xr-devops\ pull -q
      - run: |
          C:\dev\git\zrh-xr-devops\scripts\ue_build_action.py ${{github.workspace}} ${{github.ref_name}} vitruvio_host_package ${{env.CONFIG}}
      - run: |
          C:\dev\git\zrh-xr-devops\scripts\ue_run_action.py ${{github.workspace}} ${{github.ref_name}} vitruvio_host_package
  
  build-plugin:
    runs-on: [self-hosted, zrh-unreal]
    name: Build plugin
    steps:
      - uses: actions/checkout@v4
      - run: git -C C:\dev\git\zrh-xr-devops\ pull -q
      - run: |
          C:\dev\git\zrh-xr-devops\scripts\ue_build_action.py ${{github.workspace}} ${{github.ref_name}} vitruvio_plugin_build
