name: build-vitruvio

on: 
  push:
    # Careful! No fall-through for the filters.
    branches:
      - main
      - develop
      
  pull_request:
    # Careful! No fall-through for the filters.
    branches:
      - main
      - develop

jobs:
  package-host-main:
    runs-on: [self-hosted, zrh-unreal]
    name: Package host project (shipping) on main branch
    if: github.ref == 'refs/heads/main'
    steps:
      - uses: actions/checkout@v4
      - run: |
          C:\dev\git\zrh-xr-devops\scripts\ue_build_action.py ${{github.workspace}} ${{github.ref_name}} vitruvio_host_package --build-config=Shipping
      - run: |
          C:\dev\git\zrh-xr-devops\scripts\ue_run_action.py ${{github.workspace}} ${{github.ref_name}} vitruvio_host_package
  
  build-plugin-main:
    runs-on: [self-hosted, zrh-unreal]
    name: Build plugin on main branch
    if: github.ref == 'refs/heads/main'
    steps:
      - uses: actions/checkout@v4
      - run: |
          C:\dev\git\zrh-xr-devops\scripts\ue_build_action.py ${{github.workspace}} ${{github.ref_name}} vitruvio_plugin_build

  package-host-develop:
    runs-on: [self-hosted, zrh-unreal]
    name: Package host project (development) on develop branch
    if: github.ref != 'refs/heads/main'
    steps:
      - uses: actions/checkout@v4
      - run: |
          C:\dev\git\zrh-xr-devops\scripts\ue_build_action.py ${{github.workspace}} ${{github.ref_name}} vitruvio_host_package
      - run: |
          C:\dev\git\zrh-xr-devops\scripts\ue_run_action.py ${{github.workspace}} ${{github.ref_name}} vitruvio_host_package
  
  build-plugin-develop:
    runs-on: [self-hosted, zrh-unreal]
    name: Build plugin on develop branch
    if: github.ref != 'refs/heads/main'
    steps:
      - uses: actions/checkout@v4
      - run: |
          C:\dev\git\zrh-xr-devops\scripts\ue_build_action.py ${{github.workspace}} ${{github.ref_name}} vitruvio_plugin_build
